version: '3'

services:

  remarkable:
    container_name: remarkable
    image: remarkable
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 80
      - 22
