version: '3'

services:

  rm-qtcreator:
    container_name: rm-qtcreator
    image: rm-qtcreator
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - DISPLAY=:0
    volumes:
      # allow screen access
      - ~/.Xauthority:/root/.Xauthority:rw
      # allow ssh access
      - ~/.ssh:/root/.ssh
      # directory to pass projects
      - ./projects:/root/projects
