version: '3'

services:

  opkg:
    container_name: opkg
    image: opkg
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html
